[macro_parameters]
batch_size = 64
epochs = 1

[model]
name = "AlexNet"
end = 2
classifier = "./classifiers/alexnet_classifier.json"
image_size = [224, 224]

[optimizer]
name = "SGD"
learning_rate = 0.0001

[loss_function]
name = "CrossEntropyLoss"
