[macro_parameters]
batch_size = 64
epochs = 1

[model]
name = "mnasnet_0_5"
end = 16
classifier = "../classifiers/default_classifier.json"

[optimizer]
name = "SGD"
learning_rate = 0.01

[loss_function]
name = "CrossEntropyLoss"